// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Delete Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Delete', async function() {
    await driver.get("https://www.saucedemo.com/")
    await driver.manage().window().setRect({ width: 1406, height: 797 })
    await driver.findElement(By.css("*[data-test=\"username\"]")).click()
    await driver.findElement(By.css("*[data-test=\"username\"]")).sendKeys("standard_user")
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.css("*[data-test=\"password\"]")).click()
    await driver.findElement(By.css("*[data-test=\"password\"]")).sendKeys("secret_sauce")
    await driver.findElement(By.css("*[data-test=\"login-button\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")).click()
    await driver.findElement(By.css("*[data-test=\"shopping-cart-link\"]")).click()
    await driver.findElement(By.css("*[data-test=\"remove-sauce-labs-backpack\"]")).click()
    await driver.findElement(By.css("*[data-test=\"remove-sauce-labs-bike-light\"]")).click()
    await driver.close()
  })
})
